// <auto-generated />
using System;
using APIGestionale.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGestionale.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230830184334_GestionaleHR")]
    partial class GestionaleHR
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGestionale.Models.Benefits", b =>
                {
                    b.Property<int>("IDBenefit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBenefit"));

                    b.Property<string>("Benefit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeBenefit")
                        .HasColumnType("bit");

                    b.HasKey("IDBenefit");

                    b.ToTable("Benefit");
                });

            modelBuilder.Entity("APIGestionale.Models.Benefits_Contratto", b =>
                {
                    b.Property<int>("IDBenefits_Contratto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDBenefits_Contratto"));

                    b.Property<int>("IDBenefit")
                        .HasColumnType("int");

                    b.Property<int>("IDContratto")
                        .HasColumnType("int");

                    b.HasKey("IDBenefits_Contratto");

                    b.ToTable("Benefit_contratto");
                });

            modelBuilder.Entity("APIGestionale.Models.Candidato", b =>
                {
                    b.Property<int>("IDCandidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCandidato"));

                    b.Property<string>("CodiceFiscaleCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CognomeCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDCitta")
                        .HasColumnType("int");

                    b.Property<int>("IDComune")
                        .HasColumnType("int");

                    b.Property<int>("IDProvincia")
                        .HasColumnType("int");

                    b.Property<int>("IDStato")
                        .HasColumnType("int");

                    b.Property<string>("NomeCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecapitoTelCandidato")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDCandidato");

                    b.ToTable("Candidato");
                });

            modelBuilder.Entity("APIGestionale.Models.Colloquio", b =>
                {
                    b.Property<int>("IDColloquio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDColloquio"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCandidato")
                        .HasColumnType("int");

                    b.Property<int>("IDDipendente")
                        .HasColumnType("int");

                    b.Property<int>("IDHardSkill_Candidato")
                        .HasColumnType("int");

                    b.Property<int>("IDSede")
                        .HasColumnType("int");

                    b.Property<int>("IDSoftSkills_Candidato")
                        .HasColumnType("int");

                    b.Property<int>("IDTipoColloquio")
                        .HasColumnType("int");

                    b.Property<int>("IDTitolodistudio_Candidato")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valutazione")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDColloquio");

                    b.ToTable("Colloquio");
                });

            modelBuilder.Entity("APIGestionale.Models.Comune", b =>
                {
                    b.Property<int>("IDComune")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDComune"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDComune");

                    b.ToTable("Comune");
                });

            modelBuilder.Entity("APIGestionale.Models.Contratto", b =>
                {
                    b.Property<int>("IDContratto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDContratto"));

                    b.Property<int>("IDBenefits_Contratto")
                        .HasColumnType("int");

                    b.Property<int>("IDLivelloContrattuale")
                        .HasColumnType("int");

                    b.Property<int>("IDTipologiaContratto")
                        .HasColumnType("int");

                    b.Property<int>("IDTipologiaDocumento")
                        .HasColumnType("int");

                    b.HasKey("IDContratto");

                    b.ToTable("Contratto");
                });

            modelBuilder.Entity("APIGestionale.Models.Dipendente", b =>
                {
                    b.Property<int>("IdDipendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDipendente"));

                    b.Property<string>("CodiceFiscaleDipendente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CognomeDipendente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDContratto")
                        .HasColumnType("int");

                    b.Property<int>("IDHardSkills_Dipendente")
                        .HasColumnType("int");

                    b.Property<int>("IDRuolo")
                        .HasColumnType("int");

                    b.Property<int>("IDSede")
                        .HasColumnType("int");

                    b.Property<int>("IDSoftSkills_Dipendente")
                        .HasColumnType("int");

                    b.Property<int>("IDTitolidistudio_Dipendente")
                        .HasColumnType("int");

                    b.Property<string>("NomeDipendente")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDipendente");

                    b.ToTable("Dipendente");
                });

            modelBuilder.Entity("APIGestionale.Models.HardSkill_Candidato", b =>
                {
                    b.Property<int>("IDHardSkill_Candidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHardSkill_Candidato"));

                    b.Property<int>("IDCandidato")
                        .HasColumnType("int");

                    b.Property<int>("IDHardSkills")
                        .HasColumnType("int");

                    b.HasKey("IDHardSkill_Candidato");

                    b.ToTable("Hardskills_candidato");
                });

            modelBuilder.Entity("APIGestionale.Models.HardSkill_Dipendente", b =>
                {
                    b.Property<int>("IDHardSkill_Dipendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHardSkill_Dipendente"));

                    b.Property<int>("IDHardSkills")
                        .HasColumnType("int");

                    b.Property<int>("IdDipendente")
                        .HasColumnType("int");

                    b.HasKey("IDHardSkill_Dipendente");

                    b.ToTable("Hardskills_dipendente");
                });

            modelBuilder.Entity("APIGestionale.Models.HardSkills", b =>
                {
                    b.Property<int>("IDHardSkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHardSkills"));

                    b.Property<string>("DescrizioneHardSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeHardSkills")
                        .HasColumnType("bit");

                    b.HasKey("IDHardSkills");

                    b.ToTable("Hardskills");
                });

            modelBuilder.Entity("APIGestionale.Models.Livellocontrattuale", b =>
                {
                    b.Property<int>("IDLivelloContrattuale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDLivelloContrattuale"));

                    b.Property<string>("DescrizioneLivelloContrattuale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeLivelloContrattuale")
                        .HasColumnType("bit");

                    b.HasKey("IDLivelloContrattuale");

                    b.ToTable("Livellocontrattuale");
                });

            modelBuilder.Entity("APIGestionale.Models.Provincia", b =>
                {
                    b.Property<int>("IDProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDProvincia"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("APIGestionale.Models.Ruolo", b =>
                {
                    b.Property<int>("IDRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDRuolo"));

                    b.Property<string>("DescrizioneRuolo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeRuolo")
                        .HasColumnType("bit");

                    b.HasKey("IDRuolo");

                    b.ToTable("Ruolo");
                });

            modelBuilder.Entity("APIGestionale.Models.Sede", b =>
                {
                    b.Property<int>("IDSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSede"));

                    b.Property<string>("DescrizioneSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDipendente")
                        .HasColumnType("int");

                    b.Property<string>("IndirizzoSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecapitoTelSede")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDSede");

                    b.ToTable("Sedi");
                });

            modelBuilder.Entity("APIGestionale.Models.SoftSkills", b =>
                {
                    b.Property<int>("IDSoftSkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSoftSkills"));

                    b.Property<string>("DescrizioneSoftSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeSoftSkills")
                        .HasColumnType("bit");

                    b.HasKey("IDSoftSkills");

                    b.ToTable("Softskills");
                });

            modelBuilder.Entity("APIGestionale.Models.SoftSkills_Candidato", b =>
                {
                    b.Property<int>("IDSoftSkills_Candidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSoftSkills_Candidato"));

                    b.Property<int>("IDCandidato")
                        .HasColumnType("int");

                    b.Property<int>("IDSoftSkills")
                        .HasColumnType("int");

                    b.HasKey("IDSoftSkills_Candidato");

                    b.ToTable("Softskills_candidato");
                });

            modelBuilder.Entity("APIGestionale.Models.SoftSkills_Dipendente", b =>
                {
                    b.Property<int>("IDSoftSkills_Dipendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDSoftSkills_Dipendente"));

                    b.Property<int>("IDSoftSkills")
                        .HasColumnType("int");

                    b.Property<int>("IdDipendente")
                        .HasColumnType("int");

                    b.HasKey("IDSoftSkills_Dipendente");

                    b.ToTable("Softskills_dipendente");
                });

            modelBuilder.Entity("APIGestionale.Models.Stato", b =>
                {
                    b.Property<int>("IDStato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStato"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDStato");

                    b.ToTable("Stato");
                });

            modelBuilder.Entity("APIGestionale.Models.Tipologiacolloquio", b =>
                {
                    b.Property<int>("IDTipologiacolloquio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTipologiacolloquio"));

                    b.Property<string>("DescrizioneTipocolloquio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeTipocolloquio")
                        .HasColumnType("bit");

                    b.HasKey("IDTipologiacolloquio");

                    b.ToTable("Tipocolloquio");
                });

            modelBuilder.Entity("APIGestionale.Models.Tipologiacontratto", b =>
                {
                    b.Property<int>("IDTipologiacontratto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTipologiacontratto"));

                    b.Property<string>("DescrizioneTipocontratto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeTipocontratto")
                        .HasColumnType("bit");

                    b.HasKey("IDTipologiacontratto");

                    b.ToTable("Tipocontratto");
                });

            modelBuilder.Entity("APIGestionale.Models.Tipologiadocumento", b =>
                {
                    b.Property<int>("IDTipologiadocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTipologiadocumento"));

                    b.Property<string>("DescrizioneTipodocumento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeTipodocumento")
                        .HasColumnType("bit");

                    b.HasKey("IDTipologiadocumento");

                    b.ToTable("Tipodocumento");
                });

            modelBuilder.Entity("APIGestionale.Models.Titolidistudio", b =>
                {
                    b.Property<int>("IDTitolodistudio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTitolodistudio"));

                    b.Property<string>("DescrizioneTitolidistudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ModeTitolitdistudio")
                        .HasColumnType("bit");

                    b.HasKey("IDTitolodistudio");

                    b.ToTable("Titolidistudio");
                });

            modelBuilder.Entity("APIGestionale.Models.Titolodistudio_Candidato", b =>
                {
                    b.Property<int>("IDTitolodistudio_Candidato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTitolodistudio_Candidato"));

                    b.Property<int>("IDCandidato")
                        .HasColumnType("int");

                    b.Property<int>("IDTitolodistudio")
                        .HasColumnType("int");

                    b.HasKey("IDTitolodistudio_Candidato");

                    b.ToTable("Titolidistudio_candidato");
                });

            modelBuilder.Entity("APIGestionale.Models.Titolodistudio_Dipendente", b =>
                {
                    b.Property<int>("IDTitolodistudio_Dipendente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDTitolodistudio_Dipendente"));

                    b.Property<int>("IDTitolodistudio")
                        .HasColumnType("int");

                    b.Property<int>("IdDipendente")
                        .HasColumnType("int");

                    b.HasKey("IDTitolodistudio_Dipendente");

                    b.ToTable("Titolidistudio_dipendente");
                });
#pragma warning restore 612, 618
        }
    }
}
